### ISSUE TITLE
Extend either `Sojka-uvodnik/` or `StaryNovotny-tug/` by one page

### ISSUE THREAD

**Issue by Witiko** [Witiko/cstug-bulletin-2023-3-4#20]
Currently, the issue has 103 pages. We should extend either `Sojka-uvodnik/` or `StaryNovotny-tug/` by 1 page.

For `StaryNovotny-tug/`, we might add:

1. Bibliographic references to [the recordings of the talks on YouTube][1].
2. Pictures from the conference by @PetrSojka.

 [1]: https://www.youtube.com/playlist?list=PLLt9mKFAx-FZkuBBIO5ZLMNvZsD9PAs5e

**Comment by PetrSojka** [comment]
I sent some photos from Bonn to Vitek directly.

st 15. 11. 2023 v 23:08 odesílatel Vít Starý Novotný <
***@***.***> napsal:
